### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by incompletebiped** [krzysztof-ciszewski/timeular-reader#1]
I understand that this is CLI so it needs some basic knowledge, but I'm hoping you'll breakdown for me a bit more. I have the file for timeular-reader-0.1.1 but I don't understand how to start using it. I know I need to open something in terminal but nothing seems to be working. My plan is to use Clockify. I have everything I need from Clockify but I'm not sure how to start using the CLI to connect them.

**Comment by krzysztof-ciszewski** [comment]
Do you know how to run a CLI program in your terminal? When you say you have a file for timeular-reader-0.1.1 - what do you mean? Did you download the file `timeular_reader_linux` from releases? Are you running linux or windows?

**Comment by incompletebiped** [comment]
That's what I was doing wrong. I pulled the source code and not the actual release from Assets. Sorry. I was really tired.
